version: "3.8"

services:
  wireguard:
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=vpn.andyrum.com
      - SERVERPORT=51820
      - PEERS=5
      - PEERDNS=8.8.8.8
      - INTERNAL_SUBNET=10.13.13.0 # Internal VPN range
    volumes:
      - wireguard-data:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=false"
    networks:
      - public

volumes:
  wireguard-data:

networks:
  public:
    external: true
